### ISSUE TITLE
how to know pending revenue in Collection Pool after the distribution happened?

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/mad-hatter#100]
we are scanning the blockchain now to know all the revenues, but these numbers become useless if we don't track distributions (and we don't)

**Comment by Right2Rebel** [comment]
Don't quite follow... 

We know someone paid for a certain film. We know we owe that film a certain amount of money from the distribution pool. Once they claim it and we create a smart contract that amount gets distributed. Thereafter all territories the rights holder has allowed us to collect from will go directly to the rights holder.

**Comment by troggy** [comment]
> Thereafter all territories the rights holder has allowed us to collect from will go directly to the rights holder.

this is not implemented. So far RH will need to claim revenue from Collection Pool contract every time

**Comment by troggy** [comment]
this is more of a technical issue: how do we track previous distributions internally

**Comment by troggy** [comment]
how about changing `CollectionPool.distribute` to accept `region` parameter and emit it in the new `Distribution` event? Then we can sum up Deposits and Distributions per region and thus have an outstanding revenue amount

**Comment by troggy** [comment]
cc @johannbarbie

**Comment by johannbarbie** [comment]
closing in favor of https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/issues/101
