### ISSUE TITLE
Use tt

### ISSUE THREAD

**Issue by mwaa** [WhiteRabbitTheWorldIsYours/mad-hatter#103]
- Imdb id should have `tt` prefix follow up task to  [#60](https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/60)
- Cleanup to use util function [fromWei ](https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/pull/99#discussion_r440626326)

**Comment by troggy** [comment]
more tech debt: 
https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/pull/97/files#diff-a2e9345091313c02a8054c1f306fe3d8R54
https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/pull/97/files#diff-a2e9345091313c02a8054c1f306fe3d8R45

**Comment by mwaa** [comment]
Implemented
