### ISSUE TITLE
test fiat deposit with test cards

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#109]

**Comment by mwaa** [comment]
@johannbarbie Is this issue about the ongoing bugs for fiat deposits or its meant to capture production release?

**Comment by johannbarbie** [comment]
ongoing bugs. the issue was just a reminder for myself after a recent call.

**Comment by mwaa** [comment]
Closing as bugs are handled in #128
