### ISSUE TITLE
wait for payment confirmed before calling faucet

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#124]
after creating a payment, the frontend needs to wait and poll the API, until the payment is confirmed.

related code section: https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/blob/develop/packages/burner-plugin/src/ui/topupPage/index.tsx#L164-L166

=> otherwise there is a race condition, and the faucet will be always flaky.

**Comment by troggy** [comment]
duplicates #94 . Merged together
