### ISSUE TITLE
Fiat topup: country field should be a select box

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/mad-hatter#142]
As per Circle's [doc](https://developers.circle.com/reference/cards#create-card) Country field should be a 2-letter ISO 3166-1 alpha-2 code.

Let's use something like for Country field.

# Scope

- use https://github.com/country-regions/react-country-region-selector  or similar instead of plain text fields for Country

# Roles

gardener: @troggy 
worker: @Clearwood 
reviewer: [reviewer]

**Comment by Clearwood** [comment]
![Screenshot_20200729-004846](https://user-images.githubusercontent.com/11144110/88729972-52bfe100-d135-11ea-9537-ff6b2640a55f.jpg)
