### ISSUE TITLE
help with EU grant application

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#145]
For the purpose of the [EU grant](https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/files/5016257/20200629.Appel.CNECT.-.Cinemas.as.Innovation.Hubs.for.Local.Communities.pdf), we need to get the following information from Plasma Protocols:

- fill [Grant_Application_Form_Parts_to_fill.docx](https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/files/5016258/Grant_Application_Form_Parts_to_fill.docx)
- fill [DeclarationonHonour.docx](https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/files/5016259/DeclarationonHonour.docx)
- fill [LegalEntityForm-PrivateLawBody.pdf](https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/files/5016260/LegalEntityForm-PrivateLawBody.pdf)

note: "Declaration on Honour" attached signed by the legal rep of the company with blue ink. Could you get it sent by email AND get sent the physical document signed by mail to the attention of Guilhem Olive

**Comment by troggy** [comment]
shared complete docs in DM

**Comment by troggy** [comment]
all of a sudden some "Activity report" is needed. Upsizing to M

**Comment by troggy** [comment]
✅ filled the docs
✅ sent digital copy of Declaration of Honour with blue ink sig
✅ sent physical copy of DoH to Guilhem (in France already)
