### ISSUE TITLE
Fiat deposit: incorrect balance after fiat deposit

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/mad-hatter#159]
Problem: Deposit $3 from your credit card, UI shows $2.

## Scope
Most likely the problem is with displaying and bad rounding (somewhere [here](https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/pull/97/files#diff-f5d585914eaa86aed99aa2a454532049a1af0459601539dd092593548e4e5c73R54)). Fix it

**Comment by troggy** [comment]
The problem appears to be different: when user pays for the movie he actually sends transactions on the network (xdai) and pays networks fees for it. The balance user sees in his wallet is "maximum sendable balance", i.e. excludes the fee required to send a single tx. So if you make a fiat deposit of $2, you will recieve 2 xdai, but your "maximum sendable balance" will be 1.9979 xdai. The rest of the balance (0.0021 xdai) will be used for network fee.

This problem may be gone if we move on to gas-less network (rollup). Till that moment the faucet could be adjust to send to user a little larged amount than he was charged. E.g. users requests a $2 deposit, his card is charged $2, he receives 2.05 xdai in his wallet (extra 5 cents are paid by WR, enough to pay for many movies).

**Comment by Right2Rebel** [comment]
it comes down to WHO should be charged... or WHO needs to be informed of the extra charge...

It might be the credit card should be charged $2 + fee for example... it could be the charge comes out of the fee transferred to the RH... 

I wouldn't close this issue yet as it must be decided and justified before test market launch.

**Comment by Right2Rebel** [comment]
it comes down to WHO should be charged... or WHO needs to be informed of the extra charge...

It might be the credit card should be charged $2 + fee for example... it could be the charge comes out of the fee transferred to the RH...

I wouldn't close this issue yet as it must be decided and justified before test market launch.

**Comment by troggy** [comment]
started a separate issue as this one was about the incorrect balance (which is solved now by #191)

New issue: https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/issues/163
