### ISSUE TITLE
BUG: transaction not processed

### ISSUE THREAD

**Issue by Right2Rebel** [WhiteRabbitTheWorldIsYours/mad-hatter#172]

**Comment by Right2Rebel** [comment]
![Uploading Screenshot 2021-02-03 at 10.32.08.png…]()

**Comment by troggy** [comment]
@Right2Rebel screenshot wasn't uploaded. Can you desscribe what tx are you talking about and send the eth address of your account ? (you can find it by clicking Balance → Copy Icon in the header)

**Comment by troggy** [comment]
no details closing
