### ISSUE TITLE
Extension Requirements

### ISSUE THREAD

**Issue by Right2Rebel** [WhiteRabbitTheWorldIsYours/mad-hatter#179]
- Profile information
- Credit Card information/switch
- Purchase History (Rabbit Hole Access)
- Share to SOME (earn reward)
- Data request (entity requesting, data requested, offer made)
- Top 10 Lists: most popular locally, regionally, globally, most popular genres, most popular films by genre, most popular actors, most popular directors, top 10 after chosen actor/director etc. (down the rabbit hole)

**Comment by troggy** [comment]
Broken down in separate tickets:
Credit Card information/switch: #134
Share: #170 
Data collection: #182
Purchase history: #183
top 10: #184
