### ISSUE TITLE
show rights holder for the region on the movie page

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/mad-hatter#22]
## Scope
- detect the region of the visitor (e.g. using ipinfo API)
- display corresponding production company for the region as a rights holder of the movie. themoviedb.org API has production companies per region.
  Example for "Patterson":
  ```json
  {
  ...
  "production_companies": [
    {
      "id": 86041,
      "logo_path": null,
      "name": "Inkjet Productions",
      "origin_country": ""
    },
    {
      "id": 20580,
      "logo_path": "/tkFE81jJIqiFYPP8Tho57MXRQEx.png",
      "name": "Amazon Studios",
      "origin_country": "US"
    },
    {
      "id": 23437,
      "logo_path": null,
      "name": "K5 Film",
      "origin_country": "DE"
    },
    {
      "id": 26995,
      "logo_path": "/acHyNRG9qZKvr4ZlhsKlojhYeey.png",
      "name": "Animal Kingdom",
      "origin_country": "US"
    }
  ]
  ...
  }
   ```
  - if there is no production company for the region — TBD
  - if there is a production company without the region (see "Paterson" example above) — TBD

## Deliverables
- updated whiterabbit app
- updated client package published on npm

**Comment by troggy** [comment]
@Right2Rebel
1. what if there is no production company for the region?
2. what does production company without the region mean? For example "Inkjet Productions" company for "Paterson" in the example above. Do we always need to show it as a rights holder?

**Comment by troggy** [comment]
@Right2Rebel @johannbarbie 

what should the app do if streamer's location is unknown or he/she is in region where the movie wasn't released (no production company) ?

**Comment by troggy** [comment]
While waiting for the answer, I will assume that 
1. Production company without region should always get a cut
2. If there is no production company for the region and without region, show something like "There is not rights holder in your region" and allow playback

**Comment by Right2Rebel** [comment]
Let's try to recap from Bruno's session

1. Rights holders are: Producers, Co-Producers, Directors, Writers, Composers
- regardless of region 

These rights holders to be displayed ALWAYS

2. DISTRIBUTOR: Region - territory - country - media
- Producer may have sold Licensing Rights to Sales Agent. 
- In that case: Sales Agents is listed in unsold territories UNLESS Sales Agent has sold to a DISTRIBUTOR for that region, territory, country, media

**Comment by Right2Rebel** [comment]
Example...
Alan produced: Valley of Shadows
Co-producers: Them Girls (Germany) & Anna Kron (Sweden)
Sales agent: Celluloid Dreams (France)
Collecting agent: ECA (Denmark)

Alan agreed with Celluloid Dreams (CD) they can license the right to sell the film world wide any media for a €100,000 MG (advance) for being allowed to sell licenses to DISTRIBUTORS

REVENUE TERRITORY 

1. CD pays ECA €100,000 
2. CD sells FRANCE rights to Joker as DISTRIBUTOR (who may sell to broadcasters, streaming sites, theatres etc in the French territory only)
 	a. in this case JOKER is listed as DISTRIBUTOR in FRANCE
	b. if it was an unsold territory CELLULOID DREAMS would be listed as DISTRIBUTOR 
3. Joker pays CD €200,000 for the rights and keeps all France revenue
4. CD keeps €100,000 (MG) + fee + costs = €160,000
6. ECA collects €40,000 from CD for France profits and puts them into the waterfall

**Comment by Right2Rebel** [comment]
So from this we have to go into Waterfall... which is what I'd like to show you next

**Comment by Right2Rebel** [comment]
Short answer:

1. Production company is not relevant its DISTRIBUTOR or SALES AGENT. Production company will be displayed among RIGHTS HOLDERS
2. No DISTRIBUTOR means no sales - ie SALES AGENT should be listed

**Comment by Right2Rebel** [comment]
1. Production company without region should always get a cut
- Film with a sold territory goes straight to SALES AGENT (or Collecting Agent or if neither of the two - then Producer)

2. If there is no production company for the region and without region, show something like "There is not rights holder in your region" and allow playback
- No need to say anything other than displaying the DISTRIBUTOR or SALES AGENT

**Comment by troggy** [comment]
postponing this bounty till we have at least rudimental Global Registry with regional data. For now we only have global rights holders (e.g. Producer, Director, Composers, Writers)

**Comment by troggy** [comment]
to be redefined
