### ISSUE TITLE
WR Client should communicate that movie doesn't exists to the streaming site

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/mad-hatter#26]
Calling `requestPayment` for non existing movie should resolve to an object with `{ status: 'invalid movie' }` or something like this.

**Comment by Right2Rebel** [comment]
How is a film identified and payment request sent if the movie does not exist?

**Comment by troggy** [comment]
Payment may be requested by IMDB ID. Thus it may be a valid movie, but not
registered with WR

**Comment by troggy** [comment]
obsolete
