### ISSUE TITLE
review unilogin and onramps

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#66]
# Bounty

- seamless/barrier-free on-boarding UX is the single critical factor for user acquisition.
- cross-device/cross-browser account management is an unsolved challenged

## Scope

- propose possible integration of [unilogin](https://unilogin.io/) into burner design.
- review and compare onramps 

## Deliverables

- burner integration design document
- onramp analysis (countries, payment types, alternatives)

## Bounty Owner/Gardener

<@your github username> as **<Role>**

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @Clearwood @johannbarbie  / 40% 30%
bounty reviewer: name / 7%

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty [board](https://github.com/leapdao/mad-hatter/projects/2)

**Comment by johannbarbie** [comment]
## wip document here: 
https://hackmd.io/75oZZ6n9QnqMnnHtF0I4Fg

## test code:
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/web3@latest/dist/web3.min.js"></script>
    <title>This is the title of the webpage!</title>
  </head>
  <body>
    <button id="unilogin-button" ></button

    <p>
      This is an example paragraph. Anything in the <strong>body</strong> tag
      will appear on the page, just like this <strong>p</strong> tag and its
      contents.
    </p>
    <script src="https://unpkg.com/@unilogin/provider"></script>
    <script>
      const ulProvider = ULIFrameProvider.create("mainnet");
      const web3 = new Web3(ulProvider);
      web3.eth.requestAccounts().then((accounts) =>
        web3.eth
          .sendTransaction({
            from: accounts[0],
            to: "0xF80fd6F5eF91230805508bB28d75248024E50F6F",
            value: web3.utils.toWei("0.003"),
          })
          .then(console.log)
      );
    </script>
  </body>
</html>

```

## screen flow by @Clearwood here:
![wr-account-creation-flow](https://user-images.githubusercontent.com/659301/81506607-d10ba480-92f7-11ea-9c9a-0edd3ee5db00.png)

## conclusions:
- fiat onboarding by unilogin not useful (screenflow funky, wrong currency + network)
  => write ourselves, integrate wyre directly
- account creation (multisig deployment) maybe useful, reuse or write ourselves
- backup + device management useful, use uni-login iframe

next steps:
- [ ] create bounty for wyre integration. 
- [ ] work out screenflow in more detail and get feedback from team.
- [ ] create bounty for account creation prototype.

**Comment by Clearwood** [comment]
As Wyre dropped support for credit cards, we will try to integrate [Circle's Payment processing API](https://www.circle.com/en/payments-api) 
Next steps: 
[ ] discuss with the UniLogin team on how best to include their codebase 
[ ] call with the Circle Sales Team about what we need to make sure of when using their services

**Comment by johannbarbie** [comment]
>  credit cards
did we drop them? i thought circle accepts visa + mastercard?

**Comment by Clearwood** [comment]
> > credit cards
> 
> did we drop them? i thought circle accepts visa + mastercard?

No, we dropped Wyre but with circle we will be able to accept visa and mastercard

**Comment by johannbarbie** [comment]
Ah sorry, i should learn reading :)

**Comment by johannbarbie** [comment]
quick thoughts about onramp integration: https://docs.google.com/drawings/d/1LkIM7ANvpxIwtN4j2IiS31dEuP7YImQ85DYyD9LNBzc

**Comment by johannbarbie** [comment]
permanent account integration:
https://docs.google.com/drawings/d/1otUzbTXO4TNw_i6ZYn4Fs0hXcaeLlYz_Sn6oJpsBb8k

**Comment by johannbarbie** [comment]
backup integration:
https://docs.google.com/drawings/d/1gYXl44bK3Ypo-eALPOKlMdWwZtVpAkq2eAfBDWwsmO0

**Comment by troggy** [comment]
Johann "The Diagram Maker" :)

**Comment by johannbarbie** [comment]
done
