### ISSUE TITLE
Fix problems with IPInfo

### ISSUE THREAD

**Issue by Clearwood** [WhiteRabbitTheWorldIsYours/mad-hatter#74]
## Scope
- Client:
  - Firefox and Safari have problems with executing the Javascript fetch function
 - adding fallback for those browsers

## Funded by 

WhiteRabbit

## Roles
gardener: @Clearwood 50 DAI
worker: @troggy 250 DAI
reviewer:  @Clearwood 50 DAI

**Comment by Clearwood** [comment]
https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/pull/73

**Comment by troggy** [comment]
More information

Firefox:
there is no problems in vanilla Firefox. It was ad blocking extension which caused the trouble — ipinfo is blacklisted as a tracking software (very true btw)

Brave:
By default it blocks ipinfo as a tracking software.

Safari:
no idea, didn't test

**Comment by troggy** [comment]
proper solution would be to ask user's permission to get his geolocation

**Comment by johannbarbie** [comment]
@Right2Rebel will be interested
