### ISSUE TITLE
Create Integration with Circle Payment Processing API

### ISSUE THREAD

**Issue by Clearwood** [WhiteRabbitTheWorldIsYours/mad-hatter#80]
# Bounty

- create a page for the user to onramp from Fiat 

## Scope

- integrate Payment Processing API to enable User to Onramp
- save card ID in backend database, associated with the address 
- verify CVV before each Payment
- add callback for XDAI faucet

## Deliverables

- updated code

## Bounty Owner/Gardener

<@your github username> as **<Role>**

## Roles
bounty gardener: @Clearwood / 50 DAI 
bounty worker: @Clearwood  / share
bounty reviewer: name / share

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty [board](https://github.com/leapdao/mad-hatter/projects/2)

**Comment by troggy** [comment]
is there a way to use Circles without storing any card information on our side?

**Comment by Clearwood** [comment]
@troggy in no case we would store card details. We can either only allow one time payments and the user would have to reenter their details whenever they top up. Or we save their card details with circle, then we only need to keep track of the card ID.

**Comment by johannbarbie** [comment]
here a super vague mockup for frontend integration.
![onramp integration](https://user-images.githubusercontent.com/659301/83259367-34cb1400-a1b8-11ea-8719-bc8b9dd449dc.png)

**Comment by troggy** [comment]
crowdsized
<img width="337" alt="image" src="https://user-images.githubusercontent.com/163447/83262340-78784a80-a1c5-11ea-9ca6-1d3a072828dd.png">

**Comment by Clearwood** [comment]
![Image from iOS](https://user-images.githubusercontent.com/11144110/83743383-ee176700-a65a-11ea-97ae-69204420596a.jpg)

**Comment by troggy** [comment]
forked out #93 and #94
