### ISSUE TITLE
Create Faucet for XDAI according to payments in USDC

### ISSUE THREAD

**Issue by Clearwood** [WhiteRabbitTheWorldIsYours/mad-hatter#82]
# Bounty

- XDAI should be distributed to users after the payment for USDC was processed

## Scope

- provide an Endpoint for the Frontend to request a payout of XDAI
- have the frontend sign a message containing the paymentId
- recover the payment id from the signed message & check whether a payout has happened already
- check the payment status using the payment processing API
- recover the amount from API and payout user address from signed message
- mark payment ID as processed in faucet database

## Deliverables

- updated code
- deployed faucet

## Bounty Owner/Gardener

<@your github username> as **<Role>**

## Roles
bounty gardener: @Clearwood  / X DAI 
bounty worker: name / share
bounty reviewer: name / share

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty [board](https://github.com/leapdao/mad-hatter/projects/2)

**Comment by troggy** [comment]
sized 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/163447/83168250-de0efd00-a119-11ea-8e88-10b9277d9dd2.png">
