### ISSUE TITLE
Wallet: Fetch movie pricing from db

### ISSUE THREAD

**Issue by mwaa** [WhiteRabbitTheWorldIsYours/mad-hatter#88]
# Bounty
Movie pricing should be fetched via api and replace current static value

Endpoint: `http://be-dashboard.whiterabbit.one/graphql`
Query:
```graphql
{
  prices(IMDB: "336223"){
    sk
    type
    amount
    region
    fromWindow
    toWindow
  }
}
```

## Scope

- Graphl request for prices can be found on dashboard project `backend\README.md`
- Fetch movie pricing via graphql query `prices` which accepts IMDB ID. Reference [how to call graphql api using axios ](https://medium.com/@stubailo/how-to-call-a-graphql-server-with-axios-337a94ad6cf9)
- Use IP to capture region and match to [UN_M49 ](https://en.wikipedia.org/wiki/UN_M49)
- Create a function filter pricing array to get amount to use based on region, fromWindow, toWindow, [movieMedium](https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/tree/develop/packages/contracts). Please note function input should be passed from streamer site. Use javascript find function
`pricingHay.find(p => p.medium === needle.medium && p.region === needle.medium && p.from < Date.now() && p.to > Date.now)`
- If region does does exist fallback to record with region as `default`
- Medium use `EST` as default and fallback to `THEATER` if EST record does not exist
- For none existing movies use default record where priceType is WHITERABBIT. Above region and medium should apply
- The dates for the fromWindow and toWindow are always in ISO8601 date string, Amounts are strings which need to be converted
- Please not amount needs to be converted to 18 decimals to represent dai tokens. e.g 0.02 for 2 cents would be `2,000,000,000,000,000`. 

## Gain 
Ability to fetch movie pricing from movie database records. 

## Roles
bounty gardener: @mwaa 80 DAI
bounty worker:  name/share
bounty reviewer: name / share

**Comment by mwaa** [comment]
Dependent on [Dashboard PR](https://github.com/WhiteRabbitTheWorldIsYours/dashboard/pull/36)

**Comment by troggy** [comment]
> Use IP to capture region and match to UN_M49 

already done in https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/pull/73

**Comment by troggy** [comment]
crowdsized

<img width="473" alt="image" src="https://user-images.githubusercontent.com/163447/84072251-90c34300-a9d7-11ea-81a1-756c932d6d71.png">
