### ISSUE TITLE
Wallet: integrate database instead of using contract for movie tokens

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#89]
Currently using token ownership to direct funds charged to movie. Change functionality to use DB data instead

**Comment by troggy** [comment]
we are not using token ownership already. We are calling `CollectionPool.deposit` instead passing in `tokenId` (which is convertible to IMDB ID). Should we close the issue or something else needs to be done? Essential database integration is covered by #88. We can also get movie metadata (title, rightsholders etc) from the database but for now they are no different from IMDB data

**Comment by johannbarbie** [comment]
true, outdated assumptions, not needed.
