### ISSUE TITLE
test v-indentifier

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#90]
## Context
v-indentifier is a service to recognize movies. we have the following questions:

- can the code be injected into streaming pages?
- with which media players does the api work?
- does the service return the imdb?

email history and access:
```
Hey guys,

We've set up an access for you guys to test the movie database we have. It has a different setup than the previous test instance and I' ve attached the relevant guide, but you'll find it works very similarly except that your token is only valid for querying not inserting.

Api address is http://whitelist.videntifier.com or http://159.69.33.9  and your token: <ask @johannbarbie>

When you are ready to test just let me know and I'll help work out what kind of tests and integrations make sense. 

[..]

Best,
Páll 

On Tue, May 26, 2020 at 9:54 AM Páll Gunnarsson <pall.gunnarsson@videntifier.com> wrote:

    Hey guys,

[..]

    We've set up a small test instance for you guys to get started with details in the System Access attached file. This instance is not suited for accurate throughput measurements or large scale testing so we would set up a new instance if that becomes necessary.

    We've also decided to let you access the movie database that we have for testing purposes. We haven't been using it for some time so it will take a day or two to get you access to it. I'll ping you when it's ready.
[..]
```
## Scope
- set up a call and ask questions
- test API
- determine usability for WR

## Delivery
- report with recommendations

## Roles
bounty gardener: @johannbarbie  / 55 DAI
bounty worker: @Clearwood  / 460 DAI
bounty reviewer: @johannbarbie  / 35 DAI

**Comment by mwaa** [comment]
Maybe evaluate if code is injected in the streaming site, if it will auto scan/capture all playing movies or has to be manually triggered.

**Comment by johannbarbie** [comment]
would also be great to be able to get the dom element with the player back, so we can pause playback.

**Comment by Right2Rebel** [comment]
Guys - vIdentifier should have most market effect as the engine for the extension/plugin - not as a substitute or double verification of the PSS.

**Comment by johannbarbie** [comment]
reviewed, minor corrections and style changes
