### ISSUE TITLE
show balance for viewer at all time

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#92]
## Scope

- show user's xDAI balance in header instead of account and topup icons. Should be visible on all the pages (change Header component)
- when balance is clicked open `/topup` page
- on `/topup` page add the link "Deposit XDAI directly" which opens existing `/receive` page

## Roles

gardener: @troggy 30 DAI
worker: @Clearwood 
reviewer: [reviewer] 15%

**Comment by troggy** [comment]
@Right2Rebel @johannbarbie 

"streamer" is not correct word here. Streamer is someone who [creates a stream](https://en.wikipedia.org/wiki/Online_streamer), not the one who watches. I suggest to use term "viewer" instead

**Comment by johannbarbie** [comment]
yes, i like that. so overall we have the following audiences:
- viewer: user of [wallet](https://wallet.whiterabbit.one/) through popup or extension
- streamer: user of [client library](https://www.npmjs.com/package/@whiterabbitjs/client)
- rightsholder: user of [dashboard](https://dashboard.whiterabbit.one)
- admin: user of [admin interface](https://dashboard.whiterabbit.one/admin)

**Comment by Clearwood** [comment]
![image](https://user-images.githubusercontent.com/11144110/84398741-9cde1900-ac00-11ea-8ff9-f2caa173e276.png)
