### ISSUE TITLE
streamer needs to read movies from db

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/mad-hatter#96]

**Comment by troggy** [comment]
Is this issue make sense?

I think it is not needed, because:

1. streamer will still have the list of movies hardcoded as he needs the actual movie video data anyway. I don't know how we get get away from it
2. eventually, we want to support any movie including those not in WR database

**Comment by Right2Rebel** [comment]
Think I need a bit deeper explanation... a quick call?

**Comment by johannbarbie** [comment]
> actual movie video data
ah, good point. yes, we can't do this thing yet.

**Comment by troggy** [comment]
talked to Alan this morning about this thing. He agrees it is not needed
